### ISSUE TITLE
support nested json array

### ISSUE THREAD

**Issue by michael-land** [gajus/slonik-interceptor-field-name-transformation#1]
```sql
     SELECT "user".id, roles.*, operation_centers.*
      FROM user_token
        LEFT JOIN "user" ON user_token.user_id = "user".id
        -- get user roles
        CROSS JOIN LATERAL (
          SELECT coalesce(json_agg(user_role.*), '[]') roles
          FROM user_role
          WHERE user_role.user_id = "user".id
        ) roles
        -- get user operation centers
        CROSS JOIN LATERAL (
          SELECT coalesce(json_agg(user_operation_center.*), '[]') operation_centers
          FROM user_operation_center
          WHERE user_operation_center.user_id = "user".id
        ) operation_centers
```
Current
```
{
  id: 1,
  roles: [ { user_id: 1, role: 'Admin', is_default: true } ],
  operationCenters: [
    { user_id: 1, operation_center_id: 2, is_default: false },
    { user_id: 1, operation_center_id: 1, is_default: true }
  ]
}
```

Expected
```
{
  id: 1,
  roles: [ { userId: 1, role: 'Admin', isDefault: true } ],
  operationCenters: [
    { userId: 1, operationCenterId: 2, isDefault: false },
    { userId: 1, operationCenterId: 1, isDefault: true }
  ]
}
```

**Comment by michael-land** [comment]
NVM, I can change case at database level

**Comment by naftis** [comment]
Hi, I ran into the same problem. How did you change case at database level? I think it could be nice to have the slonik interceptor support this.

I feel like creating a database wide custom function would be little bit overkill. Also changing every column name separately feels error prone and laborious.

@gajus what do you think? This could be a config option and for example only apply for JSON arrays and not JSONB. Can we re-open this issue?

**Comment by joshdura** [comment]
> Hi, I ran into the same problem. How did you change case at database level? I think it could be nice to have the slonik interceptor support this.
> 
> I feel like creating a database wide custom function would be little bit overkill. Also changing every column name separately feels error prone and laborious.
> 
> @gajus what do you think? This could be a config option and for example only apply for JSON arrays and not JSONB. Can we re-open this issue?

Agreed. We are running into this as well, and it would be nice to have this feature supported in this interceptor.
