### ISSUE TITLE
Error: Cannot find module on v1.6.1

### ISSUE THREAD

**Issue by deman4ik** [gajus/slonik-interceptor-field-name-transformation#2]
`Error: Cannot find module '.../node_modules/slonik-interceptor-field-name-transformation/dist/index.js'. Please verify that the package.json has a valid "main" entry`

**Comment by deman4ik** [comment]
BTW Same issue with `slonik-interceptor-query-logging`

**Comment by gajus** [comment]
Fixed in the latest versions
